### ISSUE TITLE
Suggestion: Automate bumps

### ISSUE THREAD

**Issue by ericdallo** [littleli/scoop-clojure#168]
Hello, I just found that it seems you manually update the project with bumps, for example for clojure-lsp. First, thank you for being so fast! Second, maybe we can automate the bumps on the projects itself, WDYT?

clojure-lsp for example has a clojure-lsp-bot which bump the [homebrew ](https://github.com/clojure-lsp/homebrew-brew)formula automatically after a new release was done, we could add a new job [here](https://github.com/clojure-lsp/clojure-lsp/blob/master/.github/workflows/bump_downstreams.yml) bumping this project, we would only need to give write permission to the bot, WDYT?

**Comment by littleli** [comment]
Hi @ericdallo. It's so fast, because it's automated. After a correct manifest with `checkver` and `autoupdate` sections is in place. It's living on it's own. If you're interested please check [Excavator](https://github.com/littleli/scoop-clojure/actions) process in Github Actions section.

**Comment by ericdallo** [comment]
Oh, cool! thank you!
