### ISSUE TITLE
clojure stuck at version 1.10.3.1040 -- can't upgrade, can't uninstall

### ISSUE THREAD

**Issue by nonethewizer** [littleli/scoop-clojure#171]
PS C:\Users\tryan> scoop status
Scoop is up to date
Update is available for:
clojure: 1.10.3.1040 -> 1.10.3.1087

PS C:\Users\tryan> scoop update clojure
clojure: 1.10.3.1040 -> 1.10.3.1087
Updating 1 outdated app:
Updating 'clojure' (1.10.3.1040 -> 1.10.3.1087) [64bit]
Downloading new version
Loading clojure-tools-1.10.3.1087.zip from cache
Checking hash of clojure-tools-1.10.3.1087.zip ... ok.
Uninstalling 'clojure' (1.10.3.1040)
WARN Shim for 'cmd-clojure' is missing. Skipping.
WARN Shim for 'cmd-clj' is missing. Skipping.
Uninstalling PowerShell module 'ClojureTools'.
Removing ~\scoop\modules\ClojureTools
ERROR Cannot bind argument to parameter 'LinkName' because it is an empty string.
ERROR This application failed to update: clojure

PS C:\Users\tryan> scoop uninstall clojure
Uninstalling 'clojure' (1.10.3.1040)
WARN Shim for 'cmd-clojure' is missing. Skipping.
WARN Shim for 'cmd-clj' is missing. Skipping.
Uninstalling PowerShell module 'ClojureTools'.
Removing ~\scoop\modules\ClojureTools
ERROR Cannot bind argument to parameter 'LinkName' because it is an empty string.

PS C:\Users\tryan> scoop checkup
No problems identified!
PS C:\Users\tryan> scoop status
Scoop is up to date
Update is available for:
clojure: 1.10.3.1040 -> 1.10.3.1087

**Comment by littleli** [comment]
Checking this. I've never seen anything like this before.

My suspicion there is some unexpected whitespace somewhere because the 'ERROR' can happen when path is not escaped and command is not parsed correctly. But which command that's open question.

**Comment by jsg24** [comment]
I don't know exactly what's going on, but this is straight out of one of my PowerShell terminals.
![image](https://user-images.githubusercontent.com/1567745/195649324-e4e65340-0154-4abe-9843-c18810fc844e.png)

This doesn't explain everything because I opened up a new PowerShell after this and it had reverted back to the lower version.

**Comment by littleli** [comment]
From the screenshot it seems it used the cached version. You correctly enforced update with `-Sforce` argument. Scoop let tools to do their work, not interfering with them if possible.

**Comment by littleli** [comment]
Closing this as there is not much I can do about this issue.
