### ISSUE TITLE
Clojure On Main Bucket

### ISSUE THREAD

**Issue by SinaMobasheri** [littleli/scoop-clojure#173]
I know it's not related to this repo but I think it's a good place to ask, why Clojure need extra bucket and can't we add it to main bucket for simplicity?

**Comment by littleli** [comment]
Having this bucket allows me to have a better control over dev experience and ergonomics. In early days, this was just about how to install Clojure, but over time bucket included also a lot of additional utilities and programs written in Clojure. These utilities and programs each alone may not be eligible to be included in the `Main` bucket. In addition I have a Wiki with tutorials and issue tracker like this one, where we can discuss topics important to Clojurians. As an example I can point out what happened on MacOS homebrew where maintainers without consideration changed Clojure formula to include hard dependency on nonLTS versions of OpenJDK. Also they dismissed discussion about common developer practices. Then Alex Miller had to create community tap with proper formula and it's the one that official documentation is refering to. While this bucket cannot be considered official I'm very open to discussion about dev experience and ergonomics which is something `Main` scoop bucket maintainers (probably) cannot offer.

Adding (this) bucket is basically the equivalent operation to adding tap on MacOS and I don't see it as something that makes the whole process significantly more complex. It's all documented and steps should be clear. If not fill the issue and let's discuss what's wrong.

Btw even if the only purpose would be to have a catalogue of programs written in Clojure or supporting Clojure I consider it valuable demonstration of what people can build with Clojure (and GraalVM native-image).
