### ISSUE TITLE
Move Item error, when installing.

### ISSUE THREAD

**Issue by nitincodery** [littleli/scoop-clojure#197]
![image](https://user-images.githubusercontent.com/54881266/208241091-7de12bd9-8420-4acd-a244-c1baa175784b.png)

**Comment by littleli** [comment]
I wonder what's going on in there, it even expands wildcards correctly obviously and then reporting those files as absent? 

Does `clj` or `clojure` lead you to a REPL?

Btw this is mine output.
![wtf](https://user-images.githubusercontent.com/544082/208247419-da71034b-fa93-4daa-bbf2-6f1fe3b50a16.png)

 I'll simplify the manifest and let's see if we can get rid of this and let you know.

**Comment by littleli** [comment]
@nitincodery Please do following:

```sh
scoop uninstall clj-deps
scoop update
scoop install clj-deps
```

and let me know, I'll merge the fix, it closes probably this issue, but if you face a problem I'll reopen. Fingers crossed.

**Comment by nitincodery** [comment]
Related: I was installing clojure for first time ever.

**Comment by littleli** [comment]
Fair point. However scoop somewhat requires Powershell anyway. Command that are run during the manifest processing are executed using powershell. I'm actually also not a strong Powershell user myself, but it's what we have. Btw I had to one more fix afterwards. So hopefully now it's going to be ok.

**Comment by littleli** [comment]
@nitincodery let me know if you succeeded after the fix.

**Comment by nitincodery** [comment]
Ok I'll try again the same under cmd and powershell and let you know asap. 

Wonderful bucket for clojure! 🙂

**Comment by nitincodery** [comment]
> @nitincodery let me know if you succeeded after the fix.

Yes, now it works (tested in cmd), no issues at all.

**Comment by littleli** [comment]
@nitincodery glad it works for you.
