### ISSUE TITLE
[Bug]: Command "scoop install clj-deps" returns with message "Couldn't find manifest for 'vcredist2015'."

### ISSUE THREAD

**Issue by SarmBoJim** [littleli/scoop-clojure#199]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

scoop-clojure

### Expected/Current Behaviour

Expected command `scoop install clj-deps` to successfully install Clojure. Instead the command returned with the message `Couldn't find manifest for 'vcredist2015'.`

### Steps to Reproduce

```console
scoop install clj-deps
```

### Possible Solution

If it is documentation issue then please update documentation otherwise I do not understand what is going on as I have limited understanding of programming.

### Scoop and Buckets Version

```console
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'java' bucket:
53e72ae1 (HEAD -> master, origin/master, origin/HEAD) openjdk21: Update to version 21-6-ea

'main' bucket:
1cc9e55f0 (HEAD -> master, origin/master, origin/HEAD) jdtls: Update to version 1.20.0-202301192225

'scoop-clojure' bucket:
569adcd (HEAD -> master, origin/master, origin/HEAD) datalevin: Update to version 0.8.1
```

### Scoop Config

```console
last_update           scoop_repo                              scoop_branch
-----------           ----------                              ------------
20/01/2023 4:54:43 pm https://github.com/ScoopInstaller/Scoop master
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by littleli** [comment]
Thank you for reporting this. I believe solution to your problem is to add extras bucket and install absent package.

```sh
scoop bucket add extras
scoop install vcredist2015
```
I have to update installation instructions. Reason why I haven't found this earlier is I already have vcredist2015 installed with another package.

**Comment by SarmBoJim** [comment]
OK thank you, it is working now with those commands.
