### ISSUE TITLE
scoop update clojure not seeing 1.10.1.483 version

### ISSUE THREAD

**Issue by seancorfield** [littleli/scoop-clojure#2]
The wiki page has been updated to link to .483 but `scoop update clojure` still thinks .469 is the latest.

Am I missing some step?

**Comment by littleli** [comment]
> 
> 
> The wiki page has been updated to link to .483 but `scoop update clojure` still thinks .469 is the latest.
> 
> Am I missing some step?

No. Your observation is correct. Unfortunately, manifest.json file needs to be updated by hand. In addition, scoop `checkver` scriptis not reporting a new version.

The issue was fixed by #3
The current version is 1.10.1.486

Thank you for reporting this @seancorfield
