### ISSUE TITLE
Update to Clojure 1.12.0 / CLI 1.12.0.1479?

### ISSUE THREAD

**Issue by seancorfield** [littleli/scoop-clojure#212]
Once https://github.com/borkdude/deps.clj/issues/127 has been addressed.

**Comment by littleli** [comment]
Automation updated following artefacts
https://github.com/littleli/scoop-clojure/commit/4d3c0beac3e50c175090ad2b786349ae03babaa4 deps.clj
https://github.com/littleli/scoop-clojure/commit/24e66cd12e133bc601cba3016626a7889290898f clj-msi

**Comment by seancorfield** [comment]
I just went through the install process (first time on this machine with Scoop) and ended up with `DEPS_CLJ_TOOLS_VERSION` set to `1.11.1.1435` even after this (and restarting PS):

```
PS C:\Users\seanc> scoop update clj-deps
clj-deps: 1.12.0.1479 (latest version)
Latest versions for all apps are installed! For more information try 'scoop status'
PS C:\Users\seanc> scoop status
Scoop is up to date.
Everything is ok!
PS C:\Users\seanc>
```

Is there something specific I need to do/change?

**Comment by seancorfield** [comment]
`clj -Sforce` -- because I had `.cpcache` from a previous install and run (of the MSI installer).

**Comment by seancorfield** [comment]
In this case, Scoop would have had no idea that I had previously installed and used a different Clojure tool and created `.cpcache` in that particular folder, so I don't think it could have done anything about it.

I think the env var is a red herring -- but I don't know who created it or what it is used for?

I think if I'd done the install and moved to a different folder and tried it, things would have worked "as expected".

**Comment by borkdude** [comment]
Probably the cache hash calculated by deps.clj just was the same as with the new version? Perhaps it makes sense for the clojure CLI to bump the cache version when updating the clojure version, to avoid conflicts: 

https://github.com/clojure/brew-install/blob/7fcc4831ef924a8ab34f6b3dbd69aa81f0a0bd9c/src/main/resources/clojure/install/clojure#L327
