### ISSUE TITLE
Remove shim generation for clj/clojure

### ISSUE THREAD

**Issue by bascott** [littleli/scoop-clojure#5]
Since the clojure install auto-exports an alias for the module function that invokes clojure, it's not required to have a shim to use it on the command line.

I've encountered issues I believe occurs due to the additional indirection the shim introduces with respect to quoted arguments (https://github.com/BetterThanTomorrow/calva/issues/387#issuecomment-554601580).

**Comment by littleli** [comment]
Fix confirmed
